<?php
$listProductAttachment = $block->getData('listProductAttachment');
?>

<?php foreach ($listProductAttachment as $attachment): ?>
   	<div class="attachment-product-download" data-id-attachment="<?= $attachment['id'] ?>">
        <img src="<?= $block->getPathIcon($attachment['icon']) ?>" alt="<?= __($attachment['title']) ?>">
        <p class="title"><?= __($attachment['title']) ?><span class="limit-download"><?= $block->getCountDownload($attachment) ?? "" ?></span></p>
    </div>
<?php endforeach ?>
