<?php
/**
 * NOTICE OF LICENSE
 *
 * @author HTCMage Team
 * @copyright Copyright (c) 2020 HTCMage (https://www.htcmage.com)
 * @package HTCMage_ProductAttachment
 *
 */

use Magento\Catalog\Block\Adminhtml\Category\AssignProducts;
use Magento\Catalog\Block\Adminhtml\Category\Tab\Product;

/** @var AssignProducts $block */

/** @var Product $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="attachment_product" id="in_category_products" data-form-part="attachment_attachment_form"
       value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "HTCMage_ProductAttachment/js/assign_products": {
                "selectedProducts": <?= /* @noEscape */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
